### ISSUE TITLE
Obtaining confidence intervals after multilevel model

### ISSUE THREAD

**Issue by spenafajuri** [simongrund1/mitml#10] opened 2019-05-29 19:14 UTC
Hi,

I'm running a multiple imputation in a three-level imputation model. The code works well and I'm able to obtain reasonable pooled estimates using testEstimates. 

However, I get an error when using confint to obtain 95% confidence intervals:
Error in UseMethod("vcov") : 
  no applicable method for 'vcov' applied to an object of class "c('mitml.result', 'list')"

Any idea how to solve this?

Best wishes,
Sebastián Peña
National Institute for Health and Welfare, Finland

**Comment by simongrund1** [comment] 2019-05-30 13:49
From the error, it seems like you're trying to apply `confint` directly to the list of fitted analysis models. The proper way to calculate CIs using MI is to first pool the analyses with `testEstimates`, save that result, and run `confint` on that. Please see the [package documentation](https://cran.r-project.org/web/packages/mitml/mitml.pdf) (pages 9 and 10) for an example or type `?confint.mitml.testEstimates` in the R console to view the respective help file.

Closing this for now (not a bug).

**Closed** 2019-05-30 13:49 UTC
