### ISSUE TITLE
Potential scale reduction (Rhat, imputation phase) - What does psi implies? 

### ISSUE THREAD

**Issue by ruser1234** [simongrund1/mitml#22] opened 2023-05-25 13:56 UTC
Hello,

I am not sure if this is the right place to asks questions. If not, please excuse me.

I am currently using the package ```mitml``` to impute multilevel data with missings on two levels and I have a question about the ```summary```. I was wondering if one can only try to increase convergence by increasing n.burn or if it can also cohere with the imputation model itself. However, I am not able to grasp the meaning of the values of the potential scale reduction, especially psi. Can someone maybe help me with this?

Many thanks

**Comment by simongrund1** [comment] 2023-05-27 13:39
The different rows in the `summary()` output refer to different types of parameters in the imputation model, where `Psi` includes the variances and covariances of the random effects. Convergence tends to improve when the number of iterations is increased (i.e., by increasing `n.burn` or `n.iter` or both). However, poor convergence (i.e., large values for "R-hat") can also be a sign of model misspecification (e.g., when level-2 variables are included in the level-1 model). So if increasing the number of iterations does not help, the issue is likely with the model or data.

**Comment by simongrund1** [comment] 2023-06-07 09:00
No further response, so I'm marking this as closed (but can open again if needed).

**Closed by simongrund1** 2023-06-07 09:00 UTC
Labels: question
